#!/usr/bin/env bash
# Displays all aciveon the machine IPv4 addresses
# different way to  use ifcon, now ip is a new command and ifconfig can be missing in some os

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
